### ISSUE TITLE
如何确定Swizzle最优的M，S，B？

### ISSUE THREAD

**Issue by StarrickLiu** [reed-lau/cute-gemm#5]
在代码中有两处Swizzle配置，第一处是A和B Share Memory的Swizzle（M,S,B=3,3,3），第二处是C Share Memory的Swizzle（M,S,B=3,3,2）。

不太理解这两处Swizzle不一样的原因，修改了一下第一处A和B的Swizzle为 M,S,B=3,3,2，对修改前和修改后进行profile。

```
    static constexpr int kShmLoadSwizzleM = 3;
    static constexpr int kShmLoadSwizzleS = 3;
    static constexpr int kShmLoadSwizzleB = 2; // 原先为3

    using SmemLayoutAtom = decltype(composition(
        Swizzle<kShmLoadSwizzleB, kShmLoadSwizzleM, kShmLoadSwizzleS>{},
        make_layout(make_shape(Int<8>{}, Int<kTileK>{}),
                    make_stride(Int<kTileK>{}, Int<1>{}))));
```

修改前Profile的kernel avg duration 为 121.5191μs

修改后Profile的kernel avg duration 为 121.0709μs

另外采样了这两组bank conflict的各项指标，看上去修改后(B=2)时整体的指标更好一些。

reed老师可以讨论一下这个问题嘛？

附：profile文件

[ncu-profiles.zip](https://github.com/reed-lau/cute-gemm/files/14549759/ncu-profiles.zip)

**Comment by luliyucoordinate** [comment]
3, 2底层计算应该是一样的 QAQ（我在提交3.4.1更新的时候忘记把这个改过来了）， 之前做过一个视屏 https://www.bilibili.com/video/BV1Vx421f7TK/ 。当然我的理解也可能不对，可以讨论

**Comment by StarrickLiu** [comment]
> 3, 2底层计算应该是一样的 QAQ（我在提交3.4.1更新的时候忘记把这个改过来了）， 之前做过一个视屏 https://www.bilibili.com/video/BV1Vx421f7TK/ 。当然我的理解也可能不对，可以讨论

感谢回答！（其实我前两天刷到过这个视频还点了个赞

但在flash attention中代码似乎也有根据headdim来选择Swizzle，对我就有点疑惑。

https://github.com/Dao-AILab/flash-attention/blob/6c9e60de566800538fedad2ad5e6b7b55ca7f0c5/csrc/flash_attn/src/kernel_traits.h#L70-L83

```
    static constexpr int kBlockKSmem = kHeadDim % 64 == 0 ? 64 : 32;
    static constexpr int kBlockKGmem = kHeadDim % 128 == 0 ? 128 : (kHeadDim % 64 == 0 ? 64 : 32);
    static constexpr int kSwizzle = kBlockKSmem == 32 ? 2 : 3;


    using TiledMma = TiledMMA<
        typename Base::MMA_Atom_Arch,
        Layout<Shape<Int<kNWarps>,_1,_1>>,  // 4x1x1 or 8x1x1 thread group
        Tile<Int<16 * kNWarps>, _16, _16>>;


    using SmemLayoutAtomQ = decltype(
        composition(Swizzle<kSwizzle, 3, 3>{},
                    // This has to be kBlockKSmem, using kHeadDim gives wrong results for d=128
                    Layout<Shape<_8, Int<kBlockKSmem>>,
                           Stride<Int<kBlockKSmem>, _1>>{}));
```

3，2底层计算一样是跟3.4.1的cutlass更新有关系嘛？

**Comment by StarrickLiu** [comment]
> 3, 2底层计算应该是一样的 QAQ（我在提交3.4.1更新的时候忘记把这个改过来了）， 之前做过一个视屏 https://www.bilibili.com/video/BV1Vx421f7TK/ 。当然我的理解也可能不对，可以讨论

欸，回顾了一下图，B是行，M是元素数量，那我可以想通了
（给大佬视频点赞）
